import Head from 'next/head'
import Header from './header'
import Footer from './Footer'

export default function Layout({ children, pagina }) {
	return (
		<div>
			<Head>
				<title>GuitarLA - {pagina}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<h1 className="heading">Aprendiendo Next.js</h1>

			{children}

			<Footer />
		</div>
	)
}
