import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Baby Shop Mr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='heading'>Sitio en construcción</h1>
      <div Style="padding-left:35%">
        <Image className='siteconstruction' src="/img/siteinconstruction.jpg" width={400} height={300} alt=""/>
      </div>
    </div>
  )
}
